import re

words = 'BABAS BACAN BACAS BADAL BADAN BADAS BAGAD BAGAN BAGAR BAGAS BAHAI BAJAD BAJAN BAJAR BAJAS BALAD BALAJ BALAN ' \
        'BALAR BALAS BALAY BANAL BANAS BAÑAD BAÑAN BAÑAR BAÑAS BASAD BASAL BASAN BASAR BASAS BATAN BATAS BAYAL BAYAS ' \
        'BAZAR BAZAS CABAL CABAS CACAN CACAO CACAS CADAS CAGAD CAGAN CAGAR CAGAS CAIAN CAIAS CAJAS CALAD CALAN CALAO ' \
        'CALAR CALAS CAMAL CAMAO CAMAS CANAL CANAS CAÑAD CAÑAL CAÑAN CAÑAR CAÑAS CAPAD CAPAN CAPAR CAPAS CAPAZ CARAO ' \
        'CARAS CARAU CARAY CASAD CASAL CASAN CASAR CASAS CATAD CATAN CATAR CATAS CAVAD CAVAN CAVAR CAVAS CAYAN CAYAS ' \
        'CAZAD CAZAN CAZAR CAZAS DABAN DABAS DADAS DAGAS DAJAO DALAS DAMAS DAÑAD DAÑAN DAÑAR DAÑAS DARAN DARAS DATAD ' \
        'DATAN DATAR DATAS DAZAS FABAS FACAS FADAS FAJAD FAJAN FAJAR FAJAS FALAZ FAMAS FANAL FAÑAD FAÑAN FAÑAR FAÑAS ' \
        'FARAD FARAS FATAL FATAS FAYAS GABAN GABAR GAFAD GAFAN GAFAR GAFAS GAGAS GALAN GALAS GAMAS GANAD GANAN GANAR ' \
        'GANAS GAÑAN GAÑAS GARAS GARAY GASAS GATAS GAYAD GAYAN GAYAR GAYAS GAZAS HABAR HABAS HACAN HADAR HADAS HAGAN ' \
        'HAGAS HALAD HALAN HALAR HALAS HAPAX HARAN HARAS HAVAR HAYAL HAYAN HAYAS HAZAS JABAS JACAL JACAS JADAS JAJAY ' \
        'JALAD JALAN JALAR JALAS JAMAD JAMAN JAMAR JAMAS JAÑAS JARAL JARAS JASAD JASAN JASAR JASAS JATAS JAVAS JAYAN ' \
        'LACAD LACAN LACAR LACAS LADAS LAGAR LAJAS LAMAN LAMAS LANAR LANAS LAÑAD LAÑAN LAÑAR LAÑAS LAPAS LASAR LASAS ' \
        'LATAN LATAS LATAZ LAVAD LAVAN LAVAR LAVAS LAXAD LAXAN LAXAR LAXAS LAYAD LAYAN LAYAR LAYAS LAZAD LAZAN LAZAR ' \
        'LAZAS MACAL MACAN MACAR MACAS MAGAS MAJAD MAJAL MAJAN MAJAR MAJAS MALAR MALAS MAMAD MAMAN MAMAR MAMAS MANAD ' \
        'MANAL MANAN MANAR MANAS MAÑAS MAPAS MARAS MASAD MASAN MASAR MASAS MATAD MATAN MATAR MATAS MAYAD MAYAL MAYAN ' \
        'MAYAR MAYAS MAZAD MAZAN MAZAR MAZAS NABAB NABAL NABAR NABAS NACAR NACAS NADAD NADAL NADAN NADAR NADAS NAJAS ' \
        'NANAS NANAY NAPAS NASAL NASAS NATAL NATAS NAVAL NAVAS ÑAJAS ÑAÑAS ÑAPAS ÑATAS PACAE PACAS PACAY PAGAD PAGAN ' \
        'PAGAR PAGAS PAJAR PAJAS PALAS PALAY PANAL PANAS PAÑAL PAPAD PAPAL PAPAN PAPAR PAPAS PAPAZ PARAD PARAL PARAN ' \
        'PARAO PARAR PARAS PASAD PASAN PASAR PASAS PATAN PATAO PATAS PATAX PATAY PAVAS PAYAD PAYAN PAYAR PAYAS RABAL ' \
        'RABAS RADAL RADAR RADAS RAFAL RAFAS RAIAN RAIAS RAJAD RAJAN RAJAR RAJAS RALAS RAMAL RAMAS RANAS RAÑAS RAPAD ' \
        'RAPAN RAPAR RAPAS RAPAZ RARAS RASAD RASAN RASAR RASAS RATAS RAYAD RAYAN RAYAR RAYAS RAZAR RAZAS SACAD SACAN ' \
        'SACAR SACAS SAGAS SAGAZ SAJAD SAJAN SAJAR SAJAS SALAD SALAN SALAR SALAS SALAZ SAMAN SAMAS SANAD SANAN SANAR ' \
        'SANAS SAÑAS SAPAS SARAN SARAO SASAL SATAN SATAS SAYAL SAYAS TABAL TABAS TACAR TACAS TAHAS TAJAD TAJAN TAJAR ' \
        'TAJAS TALAD TALAN TALAR TALAS TAMAL TANAS TAÑAD TAÑAN TAÑAR TAÑAS TAPAD TAPAN TAPAR TAPAS TARAD TARAN TARAR ' \
        'TARAS TARAY TASAD TASAN TASAR TASAS TATAS TATAY TAZAD TAZAN TAZAR TAZAS VACAD VACAN VACAR VACAS VAGAD VAGAN ' \
        'VAGAR VAGAS VAHAD VAHAN VAHAR VAHAS VALAR VANAS VARAD VARAL VARAN VARAR VARAS VASAR VASAS VAYAN VAYAS YABAS ' \
        'YACAL YACAS YAGAN YAGAS YAMAO YANAS YAPAD YAPAN YAPAR YAPAS YATAI YATAY YAYAS ZACAS ZAFAD ZAFAN ZAFAR ZAFAS ' \
        'ZAGAL ZAGAS ZALAS ZANAS ZAPAD ZAPAN ZAPAR ZAPAS ZATAS ZAYAS ZAZAS '

bad_letters = 'ERUIOPSFGLZCBNTDJ'

pattern = re.compile(rf'[^{bad_letters}]+A+[^{bad_letters}]+A+[^{bad_letters}]')

matches = pattern.finditer(words)

for match in matches:
    print(match)
